name: front
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  dart_format: ^1.1.17
  webview_flutter: ^4.9.0
  url_launcher: ^6.0.20
  flutter_gemini_bot: ^0.0.4
  dio: ^5.7.0
  video_player: ^2.1.16
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  flutter_pdfview: ^1.0.4+2
  path_provider: ^2.1.4
  http: ^1.2.2
  syncfusion_flutter_charts: ^27.1.51
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/Esprit/
